### ISSUE TITLE
Ah...Illposted IRL...Bless me

### ISSUE THREAD

**Issue by SuAnita520** [Remosy/iceHocekeyIRL#2]
1. Implement MLS magnitude least square
2. Test Grad-CAM
3. Implement GAIL
4. Test GAIL

**Comment by Remosy** [comment]
Grad-CAM shows, the feature maps are not accurate

**Comment by Remosy** [comment]
<img >

**Comment by SuAnita520** [comment]
Grad-CAM shows, the feature maps are not accurate
